In [10]:
import pandas as pd

In [11]:
data = {}
for i in range(29):  # 0 to 28 inclusive
    data[str(i)] = i
    # Create the DataFrame
    df = pd.DataFrame(data, index=[0])

In [12]:
df.sample(frac=1, axis = 1, random_state=0)

2  20  23  13  11  25  27  26  5  14  ...  18  19  9  7  24  3  0  21  15  \
0  2  20  23  13  11  25  27  26  5  14  ...  18  19  9  7  24  3  0  21  15   

   12  
0  12  

[1 rows x 29 columns]

In [13]:
feature_importances = [0.00152426, 0.00020764, 0.00012705, 0.00477799, 0.00184263, 0.00030301,
0.00013304, 0.00045364, 0.00094648, 0.00040916, 0.00087954, 0.00112589,
0.00011614, 0.00079614, 0.0016075,  0.00141531, 0.00010663, 0.00238845,
0.00057058, 0.00038649, 0.00031523, 0.00211326, 0.00101214, 0.0002283,
0.00292748, 0.00193428, 0.00071139, 0.00104102, 0.00026512]

In [17]:
max(feature_importances)

0.00477799

In [5]:
split_left = df.sample(frac=1, axis = 1, random_state=0).values[0][:7]


In [7]:
[feature_importances[i] for i in split_left]

[0.00012705,
 0.00031523,
 0.0002283,
 0.00079614,
 0.00112589,
 0.00193428,
 0.00104102]

In [8]:
split_left = df.sample(frac=1, axis = 1, random_state=0).values[0][:15]
[feature_importances[i] for i in split_left]

[0.00012705,
 0.00031523,
 0.0002283,
 0.00079614,
 0.00112589,
 0.00193428,
 0.00104102,
 0.00071139,
 0.00030301,
 0.0016075,
 0.00094648,
 0.00010663,
 0.00101214,
 0.00238845,
 0.00020764]

In [14]:
split_right = df.sample(frac=1, axis = 1, random_state=0).values[0][7:]
[feature_importances[i] for i in split_right]

[0.00071139,
 0.00030301,
 0.0016075,
 0.00094648,
 0.00010663,
 0.00101214,
 0.00238845,
 0.00020764,
 0.00087954,
 0.00026512,
 0.00013304,
 0.00184263,
 0.00057058,
 0.00038649,
 0.00040916,
 0.00045364,
 0.00292748,
 0.00477799,
 0.00152426,
 0.00211326,
 0.00141531,
 0.00011614]

In [15]:
split_right = df.sample(frac=1, axis = 1, random_state=0).values[0][15:]
[feature_importances[i] for i in split_right]

[0.00087954,
 0.00026512,
 0.00013304,
 0.00184263,
 0.00057058,
 0.00038649,
 0.00040916,
 0.00045364,
 0.00292748,
 0.00477799,
 0.00152426,
 0.00211326,
 0.00141531,
 0.00011614]

In [11]:
import numpy as np

def split_matrix(x, a, b):
    """
    Chia ma trận x thành hai ma trận có cùng số hàng, số cột chồng lên nhau là a, và tỉ lệ giữa 2 phần là b.

    Parameters:
    - x: Ma trận cần chia.
    - a: Số cột chồng lên nhau.
    - b: Tỉ lệ giữa hai phần.

    Returns:
    - Hai ma trận a và b.
    """
    num_rows, num_cols = x.shape

    # Tính số cột cho mỗi phần
    cols_a = int(num_cols * a)
    cols_b = num_cols - cols_a

    # Tính số cột chồng lên nhau
    overlap_cols = int(num_cols * b)

    # Chọn ngẫu nhiên các cột cho phần a
    indices_a = np.random.choice(num_cols - overlap_cols, cols_a, replace=False)
    print(indices_a)

    # Tạo ma trận a từ các cột được chọn
    a_matrix = x[:, indices_a]

    # Tạo ma trận b từ các cột còn lại, có chồng lên phần a
    indices_b = np.setdiff1d(np.arange(num_cols), indices_a)
    b_matrix = x[:, indices_b]
    print(indices_b)

    return a_matrix, b_matrix



In [12]:
# Example usage:
np.random.seed(0)
x = np.random.rand(5, 10)  # Replace this with your actual data
a_ratio = 0.7  # Ratio of columns for part 'a'
b_ratio = 0.2  # Ratio of columns for part 'b'

a_matrix, b_matrix = split_matrix(x, a_ratio, b_ratio)

print("Matrix 'a':")
print(a_matrix)
print("\nMatrix 'b':")
print(b_matrix)

[7 5 6 0 3 4 2]
[1 8 9]
Matrix 'a':
[[0.891773   0.64589411 0.43758721 0.5488135  0.54488318 0.4236548
  0.60276338]
 [0.83261985 0.0871293  0.0202184  0.79172504 0.92559664 0.07103606
  0.56804456]
 [0.94466892 0.63992102 0.14335329 0.97861834 0.78052918 0.11827443
  0.46147936]
 [0.616934   0.6176355  0.61209572 0.26455561 0.56843395 0.0187898
  0.45615033]
 [0.1289263  0.67063787 0.21038256 0.3595079  0.06022547 0.66676672
  0.6976312 ]]

Matrix 'b':
[[0.71518937 0.96366276 0.38344152]
 [0.52889492 0.77815675 0.87001215]
 [0.79915856 0.52184832 0.41466194]
 [0.77423369 0.94374808 0.6818203 ]
 [0.43703195 0.31542835 0.36371077]]


In [ ]:
np.random.choice(num_cols - overlap_cols, cols_a, replace=False)